create table names (
  id int generated by default as identity,
  firstName varchar(20),
  lastName varchar(20)
);

insert into names (id, firstName, lastName) values(1, 'Fred', 'Flintstone');
insert into names (id, firstName, lastName) values(2, 'Wilma', 'Flintstone');
insert into names (id, firstName, lastName) values(3, 'Pebbles', 'Flintstone');
insert into names (id, firstName, lastName) values(4, 'Barney', 'Rubble');
insert into names (id, firstName, lastName) values(5, 'Betty', 'Rubble');